version: "3.9"

services:
  backend: 
    build: .
    ports: 
     - 8000:8000
    volumes: 
     - .:/app
    depends_on: 
      - database
  database: 
    image: postgres:alpine
    ports: 
      - 2345:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pollapalooza
    restart: always
    volumes:
      - db:/var/lib/postgresql/data 
volumes:
  db:
     